# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/constraints/m3_for_arty_a7.xdc

# XDC: C:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/constraints/m3_for_arty_a7_impl.xdc

# Block Designs: C:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/m3_for_arty_a7.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7 || ORIG_REF_NAME==m3_for_arty_a7} -quiet] -quiet

# IP: C:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_base_0/m3_for_arty_a7_proc_sys_reset_base_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_proc_sys_reset_base_0 || ORIG_REF_NAME==m3_for_arty_a7_proc_sys_reset_base_0} -quiet] -quiet

# IP: C:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_i_inv_dbgresetn_0/m3_for_arty_a7_i_inv_dbgresetn_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_i_inv_dbgresetn_0 || ORIG_REF_NAME==m3_for_arty_a7_i_inv_dbgresetn_0} -quiet] -quiet

# IP: C:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_i_inv_sysresetn1_0/m3_for_arty_a7_i_inv_sysresetn1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_i_inv_sysresetn1_0 || ORIG_REF_NAME==m3_for_arty_a7_i_inv_sysresetn1_0} -quiet] -quiet

# IP: C:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_clk_wiz_0_0/m3_for_arty_a7_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_clk_wiz_0_0 || ORIG_REF_NAME==m3_for_arty_a7_clk_wiz_0_0} -quiet] -quiet

# IP: C:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xlconstant_1_0/m3_for_arty_a7_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xlconstant_1_0 || ORIG_REF_NAME==m3_for_arty_a7_xlconstant_1_0} -quiet] -quiet

# IP: C:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_0/m3_for_arty_a7_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_gpio_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_gpio_0_0} -quiet] -quiet

# IP: C:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_interconnect_0_0/m3_for_arty_a7_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_interconnect_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_interconnect_0_0} -quiet] -quiet

# IP: C:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xbar_0/m3_for_arty_a7_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xbar_0 || ORIG_REF_NAME==m3_for_arty_a7_xbar_0} -quiet] -quiet

# IP: C:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xlconcat_1_0/m3_for_arty_a7_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xlconcat_1_0 || ORIG_REF_NAME==m3_for_arty_a7_xlconcat_1_0} -quiet] -quiet

# IP: C:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xlconstant_1_1/m3_for_arty_a7_xlconstant_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xlconstant_1_1 || ORIG_REF_NAME==m3_for_arty_a7_xlconstant_1_1} -quiet] -quiet

# IP: C:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_Cortex_M3_0_0/m3_for_arty_a7_Cortex_M3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_Cortex_M3_0_0 || ORIG_REF_NAME==m3_for_arty_a7_Cortex_M3_0_0} -quiet] -quiet

# IP: C:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xlconcat_0_0/m3_for_arty_a7_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xlconcat_0_0 || ORIG_REF_NAME==m3_for_arty_a7_xlconcat_0_0} -quiet] -quiet

# IP: C:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xlconstant_0_0/m3_for_arty_a7_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xlconstant_0_0 || ORIG_REF_NAME==m3_for_arty_a7_xlconstant_0_0} -quiet] -quiet

# IP: C:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_bram_ctrl_0_0/m3_for_arty_a7_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_bram_ctrl_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: C:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_blk_mem_gen_0_0/m3_for_arty_a7_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_blk_mem_gen_0_0 || ORIG_REF_NAME==m3_for_arty_a7_blk_mem_gen_0_0} -quiet] -quiet

# IP: c:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_0/m3_for_arty_a7_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_auto_pc_0 || ORIG_REF_NAME==m3_for_arty_a7_auto_pc_0} -quiet] -quiet

# XDC: c:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_base_0/m3_for_arty_a7_proc_sys_reset_base_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_proc_sys_reset_base_0 || ORIG_REF_NAME==m3_for_arty_a7_proc_sys_reset_base_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_base_0/m3_for_arty_a7_proc_sys_reset_base_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_proc_sys_reset_base_0 || ORIG_REF_NAME==m3_for_arty_a7_proc_sys_reset_base_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_base_0/m3_for_arty_a7_proc_sys_reset_base_0_ooc.xdc

# XDC: c:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_clk_wiz_0_0/m3_for_arty_a7_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_clk_wiz_0_0 || ORIG_REF_NAME==m3_for_arty_a7_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_clk_wiz_0_0/m3_for_arty_a7_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_clk_wiz_0_0 || ORIG_REF_NAME==m3_for_arty_a7_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_clk_wiz_0_0/m3_for_arty_a7_clk_wiz_0_0_late.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_clk_wiz_0_0 || ORIG_REF_NAME==m3_for_arty_a7_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_clk_wiz_0_0/m3_for_arty_a7_clk_wiz_0_0_ooc.xdc

# XDC: c:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_0/m3_for_arty_a7_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_gpio_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_0/m3_for_arty_a7_axi_gpio_0_0_ooc.xdc

# XDC: c:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_0/m3_for_arty_a7_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_gpio_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xbar_0/m3_for_arty_a7_xbar_0_ooc.xdc

# XDC: c:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_Cortex_M3_0_0/m3_for_arty_a7_Cortex_M3_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_Cortex_M3_0_0 || ORIG_REF_NAME==m3_for_arty_a7_Cortex_M3_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_bram_ctrl_0_0/m3_for_arty_a7_axi_bram_ctrl_0_0_ooc.xdc

# XDC: c:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_blk_mem_gen_0_0/m3_for_arty_a7_blk_mem_gen_0_0_ooc.xdc

# XDC: c:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_0/m3_for_arty_a7_auto_pc_0_ooc.xdc

# XDC: C:/embedded/new_vivado_project/cortex_m3_5/cortex_m3_2a/hardware/m3_for_arty_a7/block_diagram/m3_for_arty_a7_ooc.xdc
