@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Wed Mar 17 14:45:04 +0100 2021
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 77819a256541433f8004e1f4f878ad6e --incr --debug typical --relax --mt 2 -L lib_cdc_v1_0_2 -L proc_sys_reset_v5_0_13 -L xil_defaultlib -L util_vector_logic_v2_0_1 -L xlconstant_v1_1_6 -L axi_lite_ipif_v3_0_4 -L interrupt_control_v3_1_4 -L axi_gpio_v2_0_21 -L generic_baseblocks_v2_1_0 -L axi_infrastructure_v1_1_0 -L axi_register_slice_v2_1_19 -L fifo_generator_v13_2_4 -L axi_data_fifo_v2_1_18 -L axi_crossbar_v2_1_20 -L xlconcat_v2_1_3 -L axi_bram_ctrl_v4_1_1 -L blk_mem_gen_v8_4_3 -L axi_protocol_converter_v2_1_19 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_m3_for_arty_behav xil_defaultlib.tb_m3_for_arty xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto 77819a256541433f8004e1f4f878ad6e --incr --debug typical --relax --mt 2 -L lib_cdc_v1_0_2 -L proc_sys_reset_v5_0_13 -L xil_defaultlib -L util_vector_logic_v2_0_1 -L xlconstant_v1_1_6 -L axi_lite_ipif_v3_0_4 -L interrupt_control_v3_1_4 -L axi_gpio_v2_0_21 -L generic_baseblocks_v2_1_0 -L axi_infrastructure_v1_1_0 -L axi_register_slice_v2_1_19 -L fifo_generator_v13_2_4 -L axi_data_fifo_v2_1_18 -L axi_crossbar_v2_1_20 -L xlconcat_v2_1_3 -L axi_bram_ctrl_v4_1_1 -L blk_mem_gen_v8_4_3 -L axi_protocol_converter_v2_1_19 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_m3_for_arty_behav xil_defaultlib.tb_m3_for_arty xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
