@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Mar 17 14:45:18 +0100 2021
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim tb_m3_for_arty_behav -key {Behavioral:sim_1:Functional:tb_m3_for_arty} -tclbatch tb_m3_for_arty.tcl -protoinst "protoinst_files/m3_for_arty_a7.protoinst" -view C:/embedded/new_vivado_project/cortex_m3_6/cortex_m3_2a/hardware/m3_for_arty_a7/testbench/wave_files/wave_daplink.wcfg -log simulate.log"
call xsim  tb_m3_for_arty_behav -key {Behavioral:sim_1:Functional:tb_m3_for_arty} -tclbatch tb_m3_for_arty.tcl -protoinst "protoinst_files/m3_for_arty_a7.protoinst" -view C:/embedded/new_vivado_project/cortex_m3_6/cortex_m3_2a/hardware/m3_for_arty_a7/testbench/wave_files/wave_daplink.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
